controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_ville:
    path: /ville
    controller: App\Controller\VilleController::index

app_lieu:
    path: /lieu
    controller: App\Controller\LieuController::index

lieux_par_ville:
    path: /lieux/{ville}
    controller: App\Controller\LieuController::lieuxParVille